<?php
/**
 * Visual Composer Shortcode Builder.
 *
 * @package Fleurdesel
 */

/**
 * Register icon font fleurdesel.
 */
function fleurdesel_register_icon_font_fleurdesel() {
	$fonts = array(
		array( 'fh fh-champagne' => 'fh-champagne' ),
		array( 'fh fh-chat' => 'fh-chat' ),
		array( 'fh fh-chat-1' => 'fh-chat-1' ),
		array( 'fh fh-church' => 'fh-church' ),
		array( 'fh fh-compact-disc' => 'fh-compact-disc' ),
		array( 'fh fh-cupcake' => 'fh-cupcake' ),
		array( 'fh fh-cupid' => 'fh-cupid' ),
		array( 'fh fh-diamond' => 'fh-diamond' ),
		array( 'fh fh-doorknob' => 'fh-doorknob' ),
		array( 'fh fh-earrings' => 'fh-earrings' ),
		array( 'fh fh-engagement-ring' => 'fh-engagement-ring' ),
		array( 'fh fh-engagement-ring-1' => 'fh-engagement-ring-1' ),
		array( 'fh fh-engagement-ring-2' => 'fh-engagement-ring-2' ),
		array( 'fh fh-female' => 'fh-female' ),
		array( 'fh fh-film' => 'fh-film' ),
		array( 'fh fh-gift' => 'fh-gift' ),
		array( 'fh fh-heart' => 'fh-heart' ),
		array( 'fh fh-heart-1' => 'fh-heart-1' ),
		array( 'fh fh-hearts' => 'fh-hearts' ),
		array( 'fh fh-hot-drink' => 'fh-hot-drink' ),
		array( 'fh fh-house' => 'fh-house' ),
		array( 'fh fh-key' => 'fh-key' ),
		array( 'fh fh-list' => 'fh-list' ),
		array( 'fh fh-love-letter' => 'fh-love-letter' ),
		array( 'fh fh-love-letter-1' => 'fh-love-letter-1' ),
		array( 'fh fh-love-letter-2' => 'fh-love-letter-2' ),
		array( 'fh fh-male' => 'fh-male' ),
		array( 'fh fh-padlock' => 'fh-padlock' ),
		array( 'fh fh-padlock-1' => 'fh-padlock-1' ),
		array( 'fh fh-picture' => 'fh-picture' ),
		array( 'fh fh-placeholder' => 'fh-placeholder' ),
		array( 'fh fh-romantic-music' => 'fh-romantic-music' ),
		array( 'fh fh-shopping-bag2' => 'fh-shopping-bag2' ),
		array( 'fh fh-suitcase' => 'fh-suitcase' ),
		array( 'fh fh-video-camera' => 'fh-video-camera' ),
		array( 'fh fh-wedding-cake' => 'fh-wedding-cake' ),
		array( 'fh fh-wedding-invitation' => 'fh-wedding-invitation' ),
		array( 'fh fh-wedding-invitation-1' => 'fh-wedding-invitation-1' ),
		array( 'fh fh-wedding-rings' => 'fh-wedding-rings' ),
		array( 'fh fh-balloons' => 'fh-balloons' ),
		array( 'fh fh-balloons-1' => 'fh-balloons-1' ),
		array( 'fh fh-bed2' => 'fh-bed2' ),
		array( 'fh fh-bell2' => 'fh-bell2' ),
		array( 'fh fh-bible' => 'fh-bible' ),
		array( 'fh fh-bow' => 'fh-bow' ),
		array( 'fh fh-cake' => 'fh-cake' ),
		array( 'fh fh-calendar' => 'fh-calendar' ),
		array( 'fh fh-camera' => 'fh-camera' ),
		array( 'fh fh-candles' => 'fh-candles' ),
		array( 'fh fh-candles-1' => 'fh-candles-1' ),
		array( 'fh fh-icicle' => 'fh-icicle' ),
		array( 'fh fh-moon' => 'fh-moon' ),
		array( 'fh fh-moon-1' => 'fh-moon-1' ),
		array( 'fh fh-moon-2' => 'fh-moon-2' ),
		array( 'fh fh-moon-3' => 'fh-moon-3' ),
		array( 'fh fh-moon-4' => 'fh-moon-4' ),
		array( 'fh fh-moon-5' => 'fh-moon-5' ),
		array( 'fh fh-moon-6' => 'fh-moon-6' ),
		array( 'fh fh-moon-7' => 'fh-moon-7' ),
		array( 'fh fh-moon-8' => 'fh-moon-8' ),
		array( 'fh fh-moon-9' => 'fh-moon-9' ),
		array( 'fh fh-moon-10' => 'fh-moon-10' ),
		array( 'fh fh-moon-11' => 'fh-moon-11' ),
		array( 'fh fh-moon-12' => 'fh-moon-12' ),
		array( 'fh fh-moon-13' => 'fh-moon-13' ),
		array( 'fh fh-morning-rain' => 'fh-morning-rain' ),
		array( 'fh fh-morning-snow' => 'fh-morning-snow' ),
		array( 'fh fh-night-rain' => 'fh-night-rain' ),
		array( 'fh fh-night-snow' => 'fh-night-snow' ),
		array( 'fh fh-rainbow' => 'fh-rainbow' ),
		array( 'fh fh-rainbow-1' => 'fh-rainbow-1' ),
		array( 'fh fh-rainbow-2' => 'fh-rainbow-2' ),
		array( 'fh fh-raindrops' => 'fh-raindrops' ),
		array( 'fh fh-raining' => 'fh-raining' ),
		array( 'fh fh-rainy' => 'fh-rainy' ),
		array( 'fh fh-snow' => 'fh-snow' ),
		array( 'fh fh-snowflake' => 'fh-snowflake' ),
		array( 'fh fh-snowing' => 'fh-snowing' ),
		array( 'fh fh-snowing-1' => 'fh-snowing-1' ),
		array( 'fh fh-snowy' => 'fh-snowy' ),
		array( 'fh fh-stars' => 'fh-stars' ),
		array( 'fh fh-stars-1' => 'fh-stars-1' ),
		array( 'fh fh-stars-2' => 'fh-stars-2' ),
		array( 'fh fh-storm' => 'fh-storm' ),
		array( 'fh fh-storm-1' => 'fh-storm-1' ),
		array( 'fh fh-storm-2' => 'fh-storm-2' ),
		array( 'fh fh-summer-rain' => 'fh-summer-rain' ),
		array( 'fh fh-sunny' => 'fh-sunny' ),
		array( 'fh fh-sunrise' => 'fh-sunrise' ),
		array( 'fh fh-sunset' => 'fh-sunset' ),
		array( 'fh fh-sunset-1' => 'fh-sunset-1' ),
		array( 'fh fh-sunset-2' => 'fh-sunset-2' ),
		array( 'fh fh-temperature' => 'fh-temperature' ),
		array( 'fh fh-temperature-1' => 'fh-temperature-1' ),
		array( 'fh fh-temperature-2' => 'fh-temperature-2' ),
		array( 'fh fh-tide' => 'fh-tide' ),
		array( 'fh fh-tide-1' => 'fh-tide-1' ),
		array( 'fh fh-tornado' => 'fh-tornado' ),
		array( 'fh fh-umbrella2' => 'fh-umbrella2' ),
		array( 'fh fh-umbrella-1' => 'fh-umbrella-1' ),
		array( 'fh fh-umbrellas' => 'fh-umbrellas' ),
		array( 'fh fh-waves' => 'fh-waves' ),
		array( 'fh fh-weather' => 'fh-weather' ),
		array( 'fh fh-weather-1' => 'fh-weather-1' ),
		array( 'fh fh-wind' => 'fh-wind' ),
		array( 'fh fh-wind-1' => 'fh-wind-1' ),
		array( 'fh fh-wind-2' => 'fh-wind-2' ),
		array( 'fh fh-wind-3' => 'fh-wind-3' ),
		array( 'fh fh-wind-4' => 'fh-wind-4' ),
		array( 'fh fh-windy' => 'fh-windy' ),
		array( 'fh fh-bolt' => 'fh-bolt' ),
		array( 'fh fh-calm' => 'fh-calm' ),
		array( 'fh fh-celsius' => 'fh-celsius' ),
		array( 'fh fh-clouds' => 'fh-clouds' ),
		array( 'fh fh-clouds-1' => 'fh-clouds-1' ),
		array( 'fh fh-clouds-and-sun' => 'fh-clouds-and-sun' ),
		array( 'fh fh-cloudy-night' => 'fh-cloudy-night' ),
		array( 'fh fh-eclipse' => 'fh-eclipse' ),
		array( 'fh fh-farenheit' => 'fh-farenheit' ),
		array( 'fh fh-hail' => 'fh-hail' ),
		array( 'fh fh-relaxation' => 'fh-relaxation' ),
		array( 'fh fh-robe' => 'fh-robe' ),
		array( 'fh fh-sauna' => 'fh-sauna' ),
		array( 'fh fh-scent' => 'fh-scent' ),
		array( 'fh fh-shower' => 'fh-shower' ),
		array( 'fh fh-slippers' => 'fh-slippers' ),
		array( 'fh fh-spa' => 'fh-spa' ),
		array( 'fh fh-teapot' => 'fh-teapot' ),
		array( 'fh fh-towel' => 'fh-towel' ),
		array( 'fh fh-towels2' => 'fh-towels2' ),
		array( 'fh fh-washbowl' => 'fh-washbowl' ),
		array( 'fh fh-washbowl-1' => 'fh-washbowl-1' ),
		array( 'fh fh-water' => 'fh-water' ),
		array( 'fh fh-wax' => 'fh-wax' ),
		array( 'fh fh-aromatherapy' => 'fh-aromatherapy' ),
		array( 'fh fh-bamboo' => 'fh-bamboo' ),
		array( 'fh fh-candle' => 'fh-candle' ),
		array( 'fh fh-citrus' => 'fh-citrus' ),
		array( 'fh fh-cream' => 'fh-cream' ),
		array( 'fh fh-cream-1' => 'fh-cream-1' ),
		array( 'fh fh-face-mask' => 'fh-face-mask' ),
		array( 'fh fh-flower' => 'fh-flower' ),
		array( 'fh fh-herbs' => 'fh-herbs' ),
		array( 'fh fh-honey' => 'fh-honey' ),
		array( 'fh fh-hot-stones' => 'fh-hot-stones' ),
		array( 'fh fh-jacuzzi' => 'fh-jacuzzi' ),
		array( 'fh fh-lotion' => 'fh-lotion' ),
		array( 'fh fh-mortar' => 'fh-mortar' ),
		array( 'fh fh-music' => 'fh-music' ),
		array( 'fh fh-olive-oil' => 'fh-olive-oil' ),
		array( 'fh fh-caravan' => 'fh-caravan' ),
		array( 'fh fh-cctv' => 'fh-cctv' ),
		array( 'fh fh-champagne2' => 'fh-champagne2' ),
		array( 'fh fh-cocktail' => 'fh-cocktail' ),
		array( 'fh fh-coffee-cup' => 'fh-coffee-cup' ),
		array( 'fh fh-coffee-machine' => 'fh-coffee-machine' ),
		array( 'fh fh-comb' => 'fh-comb' ),
		array( 'fh fh-credit-card' => 'fh-credit-card' ),
		array( 'fh fh-customer-service' => 'fh-customer-service' ),
		array( 'fh fh-cutlery' => 'fh-cutlery' ),
		array( 'fh fh-door-hanger' => 'fh-door-hanger' ),
		array( 'fh fh-door-hanger-1' => 'fh-door-hanger-1' ),
		array( 'fh fh-door-key' => 'fh-door-key' ),
		array( 'fh fh-door-key-1' => 'fh-door-key-1' ),
		array( 'fh fh-double-bed' => 'fh-double-bed' ),
		array( 'fh fh-dumbbell' => 'fh-dumbbell' ),
		array( 'fh fh-entrance' => 'fh-entrance' ),
		array( 'fh fh-exit' => 'fh-exit' ),
		array( 'fh fh-exit-1' => 'fh-exit-1' ),
		array( 'fh fh-fast-food' => 'fh-fast-food' ),
		array( 'fh fh-fire-extinguisher' => 'fh-fire-extinguisher' ),
		array( 'fh fh-flip-flops' => 'fh-flip-flops' ),
		array( 'fh fh-gel' => 'fh-gel' ),
		array( 'fh fh-golf' => 'fh-golf' ),
		array( 'fh fh-golf-1' => 'fh-golf-1' ),
		array( 'fh fh-golf-2' => 'fh-golf-2' ),
		array( 'fh fh-golf-3' => 'fh-golf-3' ),
		array( 'fh fh-gym' => 'fh-gym' ),
		array( 'fh fh-hairdryer' => 'fh-hairdryer' ),
		array( 'fh fh-hammock' => 'fh-hammock' ),
		array( 'fh fh-hanger' => 'fh-hanger' ),
		array( 'fh fh-hose' => 'fh-hose' ),
		array( 'fh fh-hotel' => 'fh-hotel' ),
		array( 'fh fh-hotel-1' => 'fh-hotel-1' ),
		array( 'fh fh-hotel-2' => 'fh-hotel-2' ),
		array( 'fh fh-iron' => 'fh-iron' ),
		array( 'fh fh-lamp' => 'fh-lamp' ),
		array( 'fh fh-lifesaver' => 'fh-lifesaver' ),
		array( 'fh fh-lift' => 'fh-lift' ),
		array( 'fh fh-lift-1' => 'fh-lift-1' ),
		array( 'fh fh-location' => 'fh-location' ),
		array( 'fh fh-map' => 'fh-map' ),
		array( 'fh fh-microwave' => 'fh-microwave' ),
		array( 'fh fh-minibar' => 'fh-minibar' ),
		array( 'fh fh-no-smoking' => 'fh-no-smoking' ),
		array( 'fh fh-open' => 'fh-open' ),
		array( 'fh fh-oxygen-tank' => 'fh-oxygen-tank' ),
		array( 'fh fh-parking' => 'fh-parking' ),
		array( 'fh fh-reception' => 'fh-reception' ),
		array( 'fh fh-rent-a-car' => 'fh-rent-a-car' ),
		array( 'fh fh-restaurant' => 'fh-restaurant' ),
		array( 'fh fh-restaurant-1' => 'fh-restaurant-1' ),
		array( 'fh fh-room' => 'fh-room' ),
		array( 'fh fh-room-key' => 'fh-room-key' ),
		array( 'fh fh-room-service' => 'fh-room-service' ),
		array( 'fh fh-room-service-1' => 'fh-room-service-1' ),
		array( 'fh fh-safebox' => 'fh-safebox' ),
		array( 'fh fh-safebox-1' => 'fh-safebox-1' ),
		array( 'fh fh-shopping-bag' => 'fh-shopping-bag' ),
		array( 'fh fh-shower2' => 'fh-shower2' ),
		array( 'fh fh-shower-1' => 'fh-shower-1' ),
		array( 'fh fh-soda' => 'fh-soda' ),
		array( 'fh fh-soup' => 'fh-soup' ),
		array( 'fh fh-stairs' => 'fh-stairs' ),
		array( 'fh fh-stairs-1' => 'fh-stairs-1' ),
		array( 'fh fh-suitcase2' => 'fh-suitcase2' ),
		array( 'fh fh-swimming-pool' => 'fh-swimming-pool' ),
		array( 'fh fh-swimming-pool-1' => 'fh-swimming-pool-1' ),
		array( 'fh fh-taxi' => 'fh-taxi' ),
		array( 'fh fh-telephone' => 'fh-telephone' ),
		array( 'fh fh-television' => 'fh-television' ),
		array( 'fh fh-television-1' => 'fh-television-1' ),
		array( 'fh fh-ticket' => 'fh-ticket' ),
		array( 'fh fh-ticket-1' => 'fh-ticket-1' ),
		array( 'fh fh-toilet-paper' => 'fh-toilet-paper' ),
		array( 'fh fh-toilets' => 'fh-toilets' ),
		array( 'fh fh-toothpaste' => 'fh-toothpaste' ),
		array( 'fh fh-towel2' => 'fh-towel2' ),
		array( 'fh fh-towels' => 'fh-towels' ),
		array( 'fh fh-trolley' => 'fh-trolley' ),
		array( 'fh fh-trolley-1' => 'fh-trolley-1' ),
		array( 'fh fh-waiter' => 'fh-waiter' ),
		array( 'fh fh-washing-machine' => 'fh-washing-machine' ),
		array( 'fh fh-whiskey' => 'fh-whiskey' ),
		array( 'fh fh-wifi' => 'fh-wifi' ),
		array( 'fh fh-wine' => 'fh-wine' ),
		array( 'fh fh-air-conditioner' => 'fh-air-conditioner' ),
		array( 'fh fh-backpack' => 'fh-backpack' ),
		array( 'fh fh-bar' => 'fh-bar' ),
		array( 'fh fh-bath' => 'fh-bath' ),
		array( 'fh fh-bed' => 'fh-bed' ),
		array( 'fh fh-beds' => 'fh-beds' ),
		array( 'fh fh-bell' => 'fh-bell' ),
		array( 'fh fh-bellboy' => 'fh-bellboy' ),
		array( 'fh fh-bicycle' => 'fh-bicycle' ),
		array( 'fh fh-bin' => 'fh-bin' ),
		array( 'fh fh-bunk' => 'fh-bunk' ),
		array( 'fh fh-bus' => 'fh-bus' ),
		array( 'fh fh-cake2' => 'fh-cake2' ),
		array( 'fh fh-calendar2' => 'fh-calendar2' ),
		array( 'fh fh-wood-floor' => 'fh-wood-floor' ),
		array( 'fh fh-door-curtains' => 'fh-door-curtains' ),
		array( 'fh fh-sea-view' => 'fh-sea-view' ),
		array( 'fh fh-kid-play' => 'fh-kid-play' ),
		array( 'fh fh-ping-pong' => 'fh-ping-pong' ),
		array( 'fh fh-tennis-place' => 'fh-tennis-place' ),
		array( 'fh fh-fridge' => 'fh-fridge' ),
		array( 'fh fh-no-pet-allowed' => 'fh-no-pet-allowed' ),
		array( 'fh fh-iconboxung-11' => 'fh-iconboxung-11' ),
		array( 'fh fh-room-size' => 'fh-room-size' ),
		array( 'fh fh-newspapers' => 'fh-newspapers' ),
		array( 'fh fh-airport-pick-up' => 'fh-airport-pick-up' ),
		array( 'fh fh-kitchenette' => 'fh-kitchenette' ),
		array( 'fh fh-golf-place' => 'fh-golf-place' ),
		array( 'fh fh-dining-area' => 'fh-dining-area' ),
		array( 'fh fh-bedroom' => 'fh-bedroom' ),
		array( 'fh fh-guest' => 'fh-guest' ),
		array( 'fh fh-email' => 'fh-email' ),
		array( 'fh fh-balcony' => 'fh-balcony' ),
		array( 'fh fh-umbrella' => 'fh-umbrella' ),
		array( 'fh fh-close' => 'fh-close' ),
		array( 'fh fh-full' => 'fh-full' ),
		array( 'fh fh-book' => 'fh-book' ),
	);
	return $fonts;
}
add_filter( 'vc_iconpicker-type-fleurdesel', 'fleurdesel_register_icon_font_fleurdesel' );

/**
 * Enqueue font icon element for icon font.
 *
 * @param  // $font //.
 */
function fleurdesel_enqueue_icon_font_rent( $font ) {
	if ( 'fleurdesel' == $font ) {
		wp_enqueue_style( 'fleurdesel-icons', get_template_directory_uri() . '/dist/css/font-fleurdeselhotel.css', array(), '28112016' );
	}
}
add_action( 'vc_enqueue_font_icon_element', 'fleurdesel_enqueue_icon_font_fleurdesel' );

/**
 * Enqueue scripts.
 */
function fleurdesel_backend_enqueue_icon_font_fleurdesel() {
	wp_enqueue_style( 'fleurdesel-icons', get_template_directory_uri() . '/dist/css/font-fleurdeselhotel.css', array(), '28112016' );
}
add_action( 'admin_enqueue_scripts', 'fleurdesel_backend_enqueue_icon_font_fleurdesel' );

/**
 * Register iconbox content element
 */
function vcmap_fleurdesel_iconbox() {

	$params = array(
		array(
			'type'        => 'dropdown',
			'param_name'  => 'type',
			'heading'     => esc_html__( 'Icon type', 'fleurdesel' ),
			'std'         => 'icon',
			'value'       => array(
				__( 'Icon', 'fleurdesel' )  => 'icon',
				__( 'Image', 'fleurdesel' ) => 'image',
			),
		),
		array(
			'type'        => 'dropdown',
			'heading'     => __( 'Icon library', 'fleurdesel' ),
			'param_name'  => 'icon_type',
			'description' => __( 'Select icon library.', 'fleurdesel' ),
			'std'         => 'fleurdesel',
			'value'       => array(
				__( 'Fleurdesel icon', 'fleurdesel' ) => 'fleurdesel',
				__( 'Font Awesome', 'fleurdesel' )    => 'fontawesome',
			),
			'dependency'  => array(
				'element' => 'type',
				'value'   => 'icon',
			),
		),
		array(
			'type'        => 'iconpicker',
			'heading'     => __( 'Icon', 'fleurdesel' ),
			'param_name'  => 'icon_fleurdesel',
			'settings'    => array(
				'iconsPerPage' => 4000,
				'type'         => 'fleurdesel',
			),
			'dependency'  => array(
				'element' => 'icon_type',
				'value'   => 'fleurdesel',
			),
			'description' => __( 'Select icon from library.', 'fleurdesel' ),
		),
		array(
			'type'        => 'iconpicker',
			'heading'     => __( 'Icon', 'fleurdesel' ),
			'param_name'  => 'icon_fontawesome',
			'settings'    => array(
				'iconsPerPage' => 4000,
			),
			'dependency'  => array(
				'element' => 'icon_type',
				'value'   => 'fontawesome',
			),
			'description' => __( 'Select icon from library.', 'fleurdesel' ),
		),
		array(
			'type'        => 'attach_image',
			'param_name'  => 'image',
			'heading'     => esc_html__( 'Image', 'fleurdesel' ),
			'dependency'  => array(
				'element' => 'type',
				'value'   => 'image',
			),
		),
		array(
			'type'        => 'textfield',
			'param_name'  => 'title',
			'heading'     => esc_html__( 'Title', 'fleurdesel' ),
			'admin_label' => true,
		),
		array(
			'type'        => 'textarea',
			'param_name'  => 'desc',
			'heading'     => esc_html__( 'Description', 'fleurdesel' ),
			'dependency'  => array(
				'element' => 'layout',
				'value'   => array( 'vertical', 'vertical_border' ),
			),
		),
		array(
			'type'        => 'vc_link',
			'param_name'  => 'link',
			'heading'     => esc_html__( 'Title link', 'fleurdesel' ),
			'dependency'  => array(
				'element'   => 'title',
				'not_empty' => true,
			),
		),
		array(
			'type'        => 'dropdown',
			'param_name'  => 'layout',
			'heading'     => esc_html__( 'Layout', 'fleurdesel' ),
			'std'         => 'vertical',
			'value'       => array(
				__( 'Vertical', 'fleurdesel' )             => 'vertical',
				__( 'Horizontal', 'fleurdesel' )           => 'horizontal',
				__( 'Vertical with border', 'fleurdesel' ) => 'vertical_border',
			),
		),
		array(
			'type'        => 'colorpicker',
			'param_name'  => 'color',
			'heading'     => esc_html__( 'Color', 'fleurdesel' ),
		),
	);

	$params = array_merge(
		$params,
		VC_Extended_Snippets::design_options()
	);

	return array(
		'name'        => esc_html__( 'Iconbox', 'fleurdesel' ),
		'category'    => esc_html__( 'AweThemes', 'fleurdesel' ),
		'description' => esc_html__( 'Display an iconbox.', 'fleurdesel' ),
		'icon'        => FLEURDESEL_PLUGIN_URL . 'icons/awethemes.png',
		'params'      => $params,
	);
}
vc_lean_map( 'fleurdesel_iconbox', 'vcmap_fleurdesel_iconbox' );

/**
 * WPBakeryShortCode_Fleurdesel_Iconbox
 */
class WPBakeryShortCode_Fleurdesel_Iconbox extends Fleurdesel_Shortcode_Abstract {
}
